import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src: [
    {
      path: "./fonts/Inter-Regular.woff2",
      weight: '400',
      style: 'normal',
    },
    {
      path: "./fonts/Inter-Medium.woff2",
      weight: '500',
      style: 'normal',
    },
    {
      path: "./fonts/Inter-SemiBold.woff2",
      weight: '600',
      style: 'normal',
    }
  ],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
